Server:
  HostName: localhost
  HTTPPort: 8000
  RPCPort: 9090
  DisableHTTPCache: true
  MaxExecutorLogSize: 20KB
  Database: boltdb
  Databases:
    BoltDB:
      Path: ./funnel-work-dir/funnel.db
  Logger:
    Level: info
    OutputFile: ""
Scheduler:
  ScheduleRate: 1s
  ScheduleChunk: 10
  NodePingTimeout: 60000000000
  NodeInitTimeout: 300000000000
  Worker:
    WorkDir: ./sched-work-dir
  Node:
    ID: ""
    ServerAddress: localhost:9090
    Timeout: -1
    Resources:
    UpdateRate: 10s
    UpdateTimeout: 1000000000
    Logger:
      Level: info
      OutputFile: ""
Backend: local
Backends:
  HTCondor:
    Template: condor-tpl
  PBS:
    Template: pbs-tpl
  GridEngine:
    Template: sge-tpl
  SLURM:
    Template: slurm-tpl
  GCE:
    AccountFile: ""
    Project: ""
    Zone: ""
    Weights:
      PreferQuickStartup: 1.0
    CacheTTL: 60000000000
Worker:
  WorkDir: ./funnel-work-dir
  UpdateRate: 10s
  BufferSize: 11KB
  TaskReader: rpc
  TaskReaders:
    RPC:
      ServerAddress: localhost:8000
  ActiveEventWriters: 
    - rpc
    - log
  EventWriters:
    RPC:
      ServerAddress: localhost:8000
      UpdateTimeout: 1s
  Logger:
    Level: info
    OutputFile: ""
Dynamo:
  TableBasename: set-by-yaml
Storage:
  Local:
    AllowedDirs:
      - ./
      - anotherdir
