package main

import "github.com/buchanae/roger/roger"

// TODO how to determine if this should have a pointer receiver?
func (c Config) RogerVals() map[string]roger.Val {
	return map[string]roger.Val{
		"Server.Name":                                        roger.NewVal([]string{"Server", "Name"}, "Server name.", &c.Server.Name),
		"Server.HostName":                                    roger.NewVal([]string{"Server", "HostName"}, "Server host name", &c.Server.HostName),
		"Server.HTTPPort":                                    roger.NewVal([]string{"Server", "HTTPPort"}, "", &c.Server.HTTPPort),
		"Server.RPCPort":                                     roger.NewVal([]string{"Server", "RPCPort"}, "Port to serve gRPC traffic on", &c.Server.RPCPort),
		"Server.Password":                                    roger.NewVal([]string{"Server", "Password"}, "", &c.Server.Password),
		"Server.DisableHTTPCache":                            roger.NewVal([]string{"Server", "DisableHTTPCache"}, "Disable http", &c.Server.DisableHTTPCache),
		"Server.MaxExecutorLogSize":                          roger.NewVal([]string{"Server", "MaxExecutorLogSize"}, "", &c.Server.MaxExecutorLogSize),
		"Server.Logger.Level":                                roger.NewVal([]string{"Server", "Logger", "Level"}, "Log level docs", &c.Server.Logger.Level),
		"Server.Logger.Formatter":                            roger.NewVal([]string{"Server", "Logger", "Formatter"}, "", &c.Server.Logger.Formatter),
		"Server.Logger.OutputFile":                           roger.NewVal([]string{"Server", "Logger", "OutputFile"}, "", &c.Server.Logger.OutputFile),
		"Server.Logger.Foo.FooField":                         roger.NewVal([]string{"Server", "Logger", "Foo", "FooField"}, "", &c.Server.Logger.Foo.FooField),
		"Server.Logger.Foo.Level":                            roger.NewVal([]string{"Server", "Logger", "Foo", "Level"}, "Foo level docs", &c.Server.Logger.Foo.Level),
		"Worker.Storage.Local.AllowedDirs":                   roger.NewVal([]string{"Worker", "Storage", "Local", "AllowedDirs"}, "", &c.Worker.Storage.Local.AllowedDirs),
		"Worker.Storage.S3.Key":                              roger.NewVal([]string{"Worker", "Storage", "S3", "Key"}, "", &c.Worker.Storage.S3.Key),
		"Worker.Storage.S3.Secret":                           roger.NewVal([]string{"Worker", "Storage", "S3", "Secret"}, "", &c.Worker.Storage.S3.Secret),
		"Worker.Storage.S3.FromEnv":                          roger.NewVal([]string{"Worker", "Storage", "S3", "FromEnv"}, "", &c.Worker.Storage.S3.FromEnv),
		"Worker.Storage.GS":                                  roger.NewVal([]string{"Worker", "Storage", "GS"}, "", &c.Worker.Storage.GS),
		"Worker.Storage.Swift.UserName":                      roger.NewVal([]string{"Worker", "Storage", "Swift", "UserName"}, "", &c.Worker.Storage.Swift.UserName),
		"Worker.Storage.Swift.Password":                      roger.NewVal([]string{"Worker", "Storage", "Swift", "Password"}, "", &c.Worker.Storage.Swift.Password),
		"Worker.Storage.Swift.AuthURL":                       roger.NewVal([]string{"Worker", "Storage", "Swift", "AuthURL"}, "", &c.Worker.Storage.Swift.AuthURL),
		"Worker.Storage.Swift.TenantName":                    roger.NewVal([]string{"Worker", "Storage", "Swift", "TenantName"}, "", &c.Worker.Storage.Swift.TenantName),
		"Worker.Storage.Swift.TenantID":                      roger.NewVal([]string{"Worker", "Storage", "Swift", "TenantID"}, "", &c.Worker.Storage.Swift.TenantID),
		"Worker.Storage.Swift.RegionName":                    roger.NewVal([]string{"Worker", "Storage", "Swift", "RegionName"}, "", &c.Worker.Storage.Swift.RegionName),
		"Worker.WorkDir":                                     roger.NewVal([]string{"Worker", "WorkDir"}, "Directory to write task files to", &c.Worker.WorkDir),
		"Worker.UpdateRate":                                  roger.NewVal([]string{"Worker", "UpdateRate"}, "How often the worker sends task log updates", &c.Worker.UpdateRate),
		"Worker.BufferSize":                                  roger.NewVal([]string{"Worker", "BufferSize"}, "Max bytes to store in-memory between updates", &c.Worker.BufferSize),
		"Worker.Logger.Level":                                roger.NewVal([]string{"Worker", "Logger", "Level"}, "Log level docs", &c.Worker.Logger.Level),
		"Worker.Logger.Formatter":                            roger.NewVal([]string{"Worker", "Logger", "Formatter"}, "", &c.Worker.Logger.Formatter),
		"Worker.Logger.OutputFile":                           roger.NewVal([]string{"Worker", "Logger", "OutputFile"}, "", &c.Worker.Logger.OutputFile),
		"Worker.Logger.Foo.FooField":                         roger.NewVal([]string{"Worker", "Logger", "Foo", "FooField"}, "", &c.Worker.Logger.Foo.FooField),
		"Worker.Logger.Foo.Level":                            roger.NewVal([]string{"Worker", "Logger", "Foo", "Level"}, "Foo level docs", &c.Worker.Logger.Foo.Level),
		"Worker.TaskReader":                                  roger.NewVal([]string{"Worker", "TaskReader"}, "", &c.Worker.TaskReader),
		"Worker.TaskReaders.RPC.ServerAddress":               roger.NewVal([]string{"Worker", "TaskReaders", "RPC", "ServerAddress"}, "RPC address of the Funnel server", &c.Worker.TaskReaders.RPC.ServerAddress),
		"Worker.TaskReaders.RPC.ServerPassword":              roger.NewVal([]string{"Worker", "TaskReaders", "RPC", "ServerPassword"}, "Password for basic auth.", &c.Worker.TaskReaders.RPC.ServerPassword),
		"Worker.TaskReaders.Dynamo.Region":                   roger.NewVal([]string{"Worker", "TaskReaders", "Dynamo", "Region"}, "", &c.Worker.TaskReaders.Dynamo.Region),
		"Worker.TaskReaders.Dynamo.Key":                      roger.NewVal([]string{"Worker", "TaskReaders", "Dynamo", "Key"}, "", &c.Worker.TaskReaders.Dynamo.Key),
		"Worker.TaskReaders.Dynamo.Secret":                   roger.NewVal([]string{"Worker", "TaskReaders", "Dynamo", "Secret"}, "", &c.Worker.TaskReaders.Dynamo.Secret),
		"Worker.TaskReaders.Dynamo.TableBasename":            roger.NewVal([]string{"Worker", "TaskReaders", "Dynamo", "TableBasename"}, "", &c.Worker.TaskReaders.Dynamo.TableBasename),
		"Worker.ActiveEventWriters":                          roger.NewVal([]string{"Worker", "ActiveEventWriters"}, "", &c.Worker.ActiveEventWriters),
		"Worker.EventWriters.RPC.ServerAddress":              roger.NewVal([]string{"Worker", "EventWriters", "RPC", "ServerAddress"}, "RPC address of the Funnel server", &c.Worker.EventWriters.RPC.ServerAddress),
		"Worker.EventWriters.RPC.ServerPassword":             roger.NewVal([]string{"Worker", "EventWriters", "RPC", "ServerPassword"}, "Password for basic auth.", &c.Worker.EventWriters.RPC.ServerPassword),
		"Worker.EventWriters.RPC.UpdateTimeout":              roger.NewVal([]string{"Worker", "EventWriters", "RPC", "UpdateTimeout"}, "Timeout duration for gRPC calls", &c.Worker.EventWriters.RPC.UpdateTimeout),
		"Worker.EventWriters.Dynamo.Region":                  roger.NewVal([]string{"Worker", "EventWriters", "Dynamo", "Region"}, "", &c.Worker.EventWriters.Dynamo.Region),
		"Worker.EventWriters.Dynamo.Key":                     roger.NewVal([]string{"Worker", "EventWriters", "Dynamo", "Key"}, "", &c.Worker.EventWriters.Dynamo.Key),
		"Worker.EventWriters.Dynamo.Secret":                  roger.NewVal([]string{"Worker", "EventWriters", "Dynamo", "Secret"}, "", &c.Worker.EventWriters.Dynamo.Secret),
		"Worker.EventWriters.Dynamo.TableBasename":           roger.NewVal([]string{"Worker", "EventWriters", "Dynamo", "TableBasename"}, "", &c.Worker.EventWriters.Dynamo.TableBasename),
		"Scheduler.ScheduleRate":                             roger.NewVal([]string{"Scheduler", "ScheduleRate"}, "How often to run a scheduler iteration.", &c.Scheduler.ScheduleRate),
		"Scheduler.ScheduleChunk":                            roger.NewVal([]string{"Scheduler", "ScheduleChunk"}, "How many tasks to schedule in one iteration.", &c.Scheduler.ScheduleChunk),
		"Scheduler.NodePingTimeout":                          roger.NewVal([]string{"Scheduler", "NodePingTimeout"}, "How long to wait for a node ping before marking it as dead", &c.Scheduler.NodePingTimeout),
		"Scheduler.NodeInitTimeout":                          roger.NewVal([]string{"Scheduler", "NodeInitTimeout"}, "How long to wait for node initialization before marking it dead", &c.Scheduler.NodeInitTimeout),
		"Scheduler.NodeDeadTimeout":                          roger.NewVal([]string{"Scheduler", "NodeDeadTimeout"}, "How long to wait before deleting a dead node from the DB.", &c.Scheduler.NodeDeadTimeout),
		"Scheduler.Node.ID":                                  roger.NewVal([]string{"Scheduler", "Node", "ID"}, "", &c.Scheduler.Node.ID),
		"Scheduler.Node.Resources.Cpus":                      roger.NewVal([]string{"Scheduler", "Node", "Resources", "Cpus"}, "A Node will automatically try to detect what resources are available to it.", &c.Scheduler.Node.Resources.Cpus),
		"Scheduler.Node.Resources.RamGb":                     roger.NewVal([]string{"Scheduler", "Node", "Resources", "RamGb"}, "A Node will automatically try to detect what resources are available to it.", &c.Scheduler.Node.Resources.RamGb),
		"Scheduler.Node.Resources.DiskGb":                    roger.NewVal([]string{"Scheduler", "Node", "Resources", "DiskGb"}, "A Node will automatically try to detect what resources are available to it.", &c.Scheduler.Node.Resources.DiskGb),
		"Scheduler.Node.Timeout":                             roger.NewVal([]string{"Scheduler", "Node", "Timeout"}, "If the node has been idle for longer than the timeout, it will shut down.", &c.Scheduler.Node.Timeout),
		"Scheduler.Node.UpdateRate":                          roger.NewVal([]string{"Scheduler", "Node", "UpdateRate"}, "How often the node sends update requests to the server.", &c.Scheduler.Node.UpdateRate),
		"Scheduler.Node.UpdateTimeout":                       roger.NewVal([]string{"Scheduler", "Node", "UpdateTimeout"}, "Timeout duration for UpdateNode() gRPC calls", &c.Scheduler.Node.UpdateTimeout),
		"Scheduler.Node.Metadata":                            roger.NewVal([]string{"Scheduler", "Node", "Metadata"}, "", &c.Scheduler.Node.Metadata),
		"Scheduler.Node.ServerAddress":                       roger.NewVal([]string{"Scheduler", "Node", "ServerAddress"}, "RPC address of the Funnel server", &c.Scheduler.Node.ServerAddress),
		"Scheduler.Node.ServerPassword":                      roger.NewVal([]string{"Scheduler", "Node", "ServerPassword"}, "Password for basic auth.", &c.Scheduler.Node.ServerPassword),
		"Scheduler.Node.Logger.Level":                        roger.NewVal([]string{"Scheduler", "Node", "Logger", "Level"}, "Log level docs", &c.Scheduler.Node.Logger.Level),
		"Scheduler.Node.Logger.Formatter":                    roger.NewVal([]string{"Scheduler", "Node", "Logger", "Formatter"}, "", &c.Scheduler.Node.Logger.Formatter),
		"Scheduler.Node.Logger.OutputFile":                   roger.NewVal([]string{"Scheduler", "Node", "Logger", "OutputFile"}, "", &c.Scheduler.Node.Logger.OutputFile),
		"Scheduler.Node.Logger.Foo.FooField":                 roger.NewVal([]string{"Scheduler", "Node", "Logger", "Foo", "FooField"}, "", &c.Scheduler.Node.Logger.Foo.FooField),
		"Scheduler.Node.Logger.Foo.Level":                    roger.NewVal([]string{"Scheduler", "Node", "Logger", "Foo", "Level"}, "Foo level docs", &c.Scheduler.Node.Logger.Foo.Level),
		"Scheduler.Logger.Level":                             roger.NewVal([]string{"Scheduler", "Logger", "Level"}, "Log level docs", &c.Scheduler.Logger.Level),
		"Scheduler.Logger.Formatter":                         roger.NewVal([]string{"Scheduler", "Logger", "Formatter"}, "", &c.Scheduler.Logger.Formatter),
		"Scheduler.Logger.OutputFile":                        roger.NewVal([]string{"Scheduler", "Logger", "OutputFile"}, "", &c.Scheduler.Logger.OutputFile),
		"Scheduler.Logger.Foo.FooField":                      roger.NewVal([]string{"Scheduler", "Logger", "Foo", "FooField"}, "", &c.Scheduler.Logger.Foo.FooField),
		"Scheduler.Logger.Foo.Level":                         roger.NewVal([]string{"Scheduler", "Logger", "Foo", "Level"}, "Foo level docs", &c.Scheduler.Logger.Foo.Level),
		"Scheduler.Worker.Storage.Local.AllowedDirs":         roger.NewVal([]string{"Scheduler", "Worker", "Storage", "Local", "AllowedDirs"}, "", &c.Scheduler.Worker.Storage.Local.AllowedDirs),
		"Scheduler.Worker.Storage.S3.Key":                    roger.NewVal([]string{"Scheduler", "Worker", "Storage", "S3", "Key"}, "", &c.Scheduler.Worker.Storage.S3.Key),
		"Scheduler.Worker.Storage.S3.Secret":                 roger.NewVal([]string{"Scheduler", "Worker", "Storage", "S3", "Secret"}, "", &c.Scheduler.Worker.Storage.S3.Secret),
		"Scheduler.Worker.Storage.S3.FromEnv":                roger.NewVal([]string{"Scheduler", "Worker", "Storage", "S3", "FromEnv"}, "", &c.Scheduler.Worker.Storage.S3.FromEnv),
		"Scheduler.Worker.Storage.GS":                        roger.NewVal([]string{"Scheduler", "Worker", "Storage", "GS"}, "", &c.Scheduler.Worker.Storage.GS),
		"Scheduler.Worker.Storage.Swift.UserName":            roger.NewVal([]string{"Scheduler", "Worker", "Storage", "Swift", "UserName"}, "", &c.Scheduler.Worker.Storage.Swift.UserName),
		"Scheduler.Worker.Storage.Swift.Password":            roger.NewVal([]string{"Scheduler", "Worker", "Storage", "Swift", "Password"}, "", &c.Scheduler.Worker.Storage.Swift.Password),
		"Scheduler.Worker.Storage.Swift.AuthURL":             roger.NewVal([]string{"Scheduler", "Worker", "Storage", "Swift", "AuthURL"}, "", &c.Scheduler.Worker.Storage.Swift.AuthURL),
		"Scheduler.Worker.Storage.Swift.TenantName":          roger.NewVal([]string{"Scheduler", "Worker", "Storage", "Swift", "TenantName"}, "", &c.Scheduler.Worker.Storage.Swift.TenantName),
		"Scheduler.Worker.Storage.Swift.TenantID":            roger.NewVal([]string{"Scheduler", "Worker", "Storage", "Swift", "TenantID"}, "", &c.Scheduler.Worker.Storage.Swift.TenantID),
		"Scheduler.Worker.Storage.Swift.RegionName":          roger.NewVal([]string{"Scheduler", "Worker", "Storage", "Swift", "RegionName"}, "", &c.Scheduler.Worker.Storage.Swift.RegionName),
		"Scheduler.Worker.WorkDir":                           roger.NewVal([]string{"Scheduler", "Worker", "WorkDir"}, "Directory to write task files to", &c.Scheduler.Worker.WorkDir),
		"Scheduler.Worker.UpdateRate":                        roger.NewVal([]string{"Scheduler", "Worker", "UpdateRate"}, "How often the worker sends task log updates", &c.Scheduler.Worker.UpdateRate),
		"Scheduler.Worker.BufferSize":                        roger.NewVal([]string{"Scheduler", "Worker", "BufferSize"}, "Max bytes to store in-memory between updates", &c.Scheduler.Worker.BufferSize),
		"Scheduler.Worker.Logger.Level":                      roger.NewVal([]string{"Scheduler", "Worker", "Logger", "Level"}, "Log level docs", &c.Scheduler.Worker.Logger.Level),
		"Scheduler.Worker.Logger.Formatter":                  roger.NewVal([]string{"Scheduler", "Worker", "Logger", "Formatter"}, "", &c.Scheduler.Worker.Logger.Formatter),
		"Scheduler.Worker.Logger.OutputFile":                 roger.NewVal([]string{"Scheduler", "Worker", "Logger", "OutputFile"}, "", &c.Scheduler.Worker.Logger.OutputFile),
		"Scheduler.Worker.Logger.Foo.FooField":               roger.NewVal([]string{"Scheduler", "Worker", "Logger", "Foo", "FooField"}, "", &c.Scheduler.Worker.Logger.Foo.FooField),
		"Scheduler.Worker.Logger.Foo.Level":                  roger.NewVal([]string{"Scheduler", "Worker", "Logger", "Foo", "Level"}, "Foo level docs", &c.Scheduler.Worker.Logger.Foo.Level),
		"Scheduler.Worker.TaskReader":                        roger.NewVal([]string{"Scheduler", "Worker", "TaskReader"}, "", &c.Scheduler.Worker.TaskReader),
		"Scheduler.Worker.TaskReaders.RPC.ServerAddress":     roger.NewVal([]string{"Scheduler", "Worker", "TaskReaders", "RPC", "ServerAddress"}, "RPC address of the Funnel server", &c.Scheduler.Worker.TaskReaders.RPC.ServerAddress),
		"Scheduler.Worker.TaskReaders.RPC.ServerPassword":    roger.NewVal([]string{"Scheduler", "Worker", "TaskReaders", "RPC", "ServerPassword"}, "Password for basic auth.", &c.Scheduler.Worker.TaskReaders.RPC.ServerPassword),
		"Scheduler.Worker.TaskReaders.Dynamo.Region":         roger.NewVal([]string{"Scheduler", "Worker", "TaskReaders", "Dynamo", "Region"}, "", &c.Scheduler.Worker.TaskReaders.Dynamo.Region),
		"Scheduler.Worker.TaskReaders.Dynamo.Key":            roger.NewVal([]string{"Scheduler", "Worker", "TaskReaders", "Dynamo", "Key"}, "", &c.Scheduler.Worker.TaskReaders.Dynamo.Key),
		"Scheduler.Worker.TaskReaders.Dynamo.Secret":         roger.NewVal([]string{"Scheduler", "Worker", "TaskReaders", "Dynamo", "Secret"}, "", &c.Scheduler.Worker.TaskReaders.Dynamo.Secret),
		"Scheduler.Worker.TaskReaders.Dynamo.TableBasename":  roger.NewVal([]string{"Scheduler", "Worker", "TaskReaders", "Dynamo", "TableBasename"}, "", &c.Scheduler.Worker.TaskReaders.Dynamo.TableBasename),
		"Scheduler.Worker.ActiveEventWriters":                roger.NewVal([]string{"Scheduler", "Worker", "ActiveEventWriters"}, "", &c.Scheduler.Worker.ActiveEventWriters),
		"Scheduler.Worker.EventWriters.RPC.ServerAddress":    roger.NewVal([]string{"Scheduler", "Worker", "EventWriters", "RPC", "ServerAddress"}, "RPC address of the Funnel server", &c.Scheduler.Worker.EventWriters.RPC.ServerAddress),
		"Scheduler.Worker.EventWriters.RPC.ServerPassword":   roger.NewVal([]string{"Scheduler", "Worker", "EventWriters", "RPC", "ServerPassword"}, "Password for basic auth.", &c.Scheduler.Worker.EventWriters.RPC.ServerPassword),
		"Scheduler.Worker.EventWriters.RPC.UpdateTimeout":    roger.NewVal([]string{"Scheduler", "Worker", "EventWriters", "RPC", "UpdateTimeout"}, "Timeout duration for gRPC calls", &c.Scheduler.Worker.EventWriters.RPC.UpdateTimeout),
		"Scheduler.Worker.EventWriters.Dynamo.Region":        roger.NewVal([]string{"Scheduler", "Worker", "EventWriters", "Dynamo", "Region"}, "", &c.Scheduler.Worker.EventWriters.Dynamo.Region),
		"Scheduler.Worker.EventWriters.Dynamo.Key":           roger.NewVal([]string{"Scheduler", "Worker", "EventWriters", "Dynamo", "Key"}, "", &c.Scheduler.Worker.EventWriters.Dynamo.Key),
		"Scheduler.Worker.EventWriters.Dynamo.Secret":        roger.NewVal([]string{"Scheduler", "Worker", "EventWriters", "Dynamo", "Secret"}, "", &c.Scheduler.Worker.EventWriters.Dynamo.Secret),
		"Scheduler.Worker.EventWriters.Dynamo.TableBasename": roger.NewVal([]string{"Scheduler", "Worker", "EventWriters", "Dynamo", "TableBasename"}, "", &c.Scheduler.Worker.EventWriters.Dynamo.TableBasename),
		"Scheduler.Backend":                                  roger.NewVal([]string{"Scheduler", "Backend"}, "", &c.Scheduler.Backend),
		"Scheduler.Backends.Local":                           roger.NewVal([]string{"Scheduler", "Backends", "Local"}, "", &c.Scheduler.Backends.Local),
		"Scheduler.Backends.HTCondor.Template":               roger.NewVal([]string{"Scheduler", "Backends", "HTCondor", "Template"}, "", &c.Scheduler.Backends.HTCondor.Template),
		"Scheduler.Backends.SLURM.Template":                  roger.NewVal([]string{"Scheduler", "Backends", "SLURM", "Template"}, "", &c.Scheduler.Backends.SLURM.Template),
		"Scheduler.Backends.PBS.Template":                    roger.NewVal([]string{"Scheduler", "Backends", "PBS", "Template"}, "", &c.Scheduler.Backends.PBS.Template),
		"Scheduler.Backends.GridEngine.Template":             roger.NewVal([]string{"Scheduler", "Backends", "GridEngine", "Template"}, "", &c.Scheduler.Backends.GridEngine.Template),
		"Scheduler.Backends.OpenStack.KeyPair":               roger.NewVal([]string{"Scheduler", "Backends", "OpenStack", "KeyPair"}, "", &c.Scheduler.Backends.OpenStack.KeyPair),
		"Scheduler.Backends.OpenStack.ConfigPath":            roger.NewVal([]string{"Scheduler", "Backends", "OpenStack", "ConfigPath"}, "", &c.Scheduler.Backends.OpenStack.ConfigPath),
		"Scheduler.Backends.GCE.AccountFile":                 roger.NewVal([]string{"Scheduler", "Backends", "GCE", "AccountFile"}, "", &c.Scheduler.Backends.GCE.AccountFile),
		"Scheduler.Backends.GCE.Project":                     roger.NewVal([]string{"Scheduler", "Backends", "GCE", "Project"}, "", &c.Scheduler.Backends.GCE.Project),
		"Scheduler.Backends.GCE.Zone":                        roger.NewVal([]string{"Scheduler", "Backends", "GCE", "Zone"}, "", &c.Scheduler.Backends.GCE.Zone),
		"Scheduler.Backends.GCE.Weights.PreferQuickStartup":  roger.NewVal([]string{"Scheduler", "Backends", "GCE", "Weights", "PreferQuickStartup"}, "", &c.Scheduler.Backends.GCE.Weights.PreferQuickStartup),
		"Scheduler.Backends.GCE.CacheTTL":                    roger.NewVal([]string{"Scheduler", "Backends", "GCE", "CacheTTL"}, "", &c.Scheduler.Backends.GCE.CacheTTL),
		"Log.Level":                                          roger.NewVal([]string{"Log", "Level"}, "Log level docs", &c.Log.Level),
		"Log.Formatter":                                      roger.NewVal([]string{"Log", "Formatter"}, "", &c.Log.Formatter),
		"Log.OutputFile":                                     roger.NewVal([]string{"Log", "OutputFile"}, "", &c.Log.OutputFile),
		"Log.Foo.FooField":                                   roger.NewVal([]string{"Log", "Foo", "FooField"}, "", &c.Log.Foo.FooField),
		"Log.Foo.Level":                                      roger.NewVal([]string{"Log", "Foo", "Level"}, "Foo level docs", &c.Log.Foo.Level),
		"Dynamo.Region":                                      roger.NewVal([]string{"Dynamo", "Region"}, "", &c.Dynamo.Region),
		"Dynamo.Key":                                         roger.NewVal([]string{"Dynamo", "Key"}, "", &c.Dynamo.Key),
		"Dynamo.Secret":                                      roger.NewVal([]string{"Dynamo", "Secret"}, "", &c.Dynamo.Secret),
		"Dynamo.TableBasename":                               roger.NewVal([]string{"Dynamo", "TableBasename"}, "", &c.Dynamo.TableBasename),
	}
}
